### ISSUE TITLE
errno 2 when executing commands

### ISSUE THREAD

**Issue by yanokwa** [SublimeText/SublimeHg#1]
i'm using sublime dev build 2083, sublimehg 41a2c3c0e9fe1ffe91a6, and hg 1.9 from macports.

in command line mode when i enter 'status' results in "SublimeHg:err:[Errno 2] No such file or directory. 

menu mode isn't working that well either. i get the list of commands, but all of them result in a similar message.

**Comment by guillermooo** [comment]
Is the `hg` executable on your `$PATH`?  You can check with a build system like so:

```
{ "cmd": ["hg", "help"] }
```

Mercurial's help topics should be printed to the output panel. (Note you may need to change the executable's name.)

**Comment by yanokwa** [comment]
not super sure i did this correctly, but the output i get is ..

[Errno 2] No such file or directory
[Finished]

i'm pretty sure hg is on my path..

localhost: > echo $PATH
/opt/local/bin:/opt/local/sbin:/opt/subversion/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/usr/texbin:/usr/local/android/tools:/usr/local/android/platform-tools:/opt/local/Library/Frameworks/Python.framework/Versions/2.6/bin

localhost: > which hg
/opt/local/bin/hg

but if i set "packages.sublime_hg.hg_exe": "/opt/local/bin/hg" things seem to work (wasn't working with the non-dev channel though)

**Comment by yanokwa** [comment]
ah, crap. forgot that i symlinked to the python bin folder. i was the bug. consider this fixed.

**Comment by chrisdkemper** [comment]
I'm having some similar problems here, I get the same error code and can't execute any commands. 

I'm working on a Mac and the path to hg is included in $PATH and I'm unsure where to go from here. 

I'd ideally like to get the plugin working sooner rather than later as I'd like to include in something I'm working on, but since I can't get it to work I can't include it.

Do you have any idea where I can go from here?

**Comment by guillermooo** [comment]
Try specifying the absolute path to the hg executable in the `packages.sublime_hg.hg_exe` setting. Your shell's `$PATH` variable might be different to what Sublime Text sees.

To check the `$PATH` seen by ST, run this in the console:

```
os.expandvars("$PATH")
```

**Comment by chrisdkemper** [comment]
I ran that command in the Sublime Text console and got an error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'os' is not defined

How do I change the packages.sublime_hg.hg_exe setting?

**Comment by guillermooo** [comment]
Yeah, you probably need to run `import os` first in the console too.

To change the aforementioned setting, go to `Preferences -> Global Settings - User` and put it there.

**Comment by chrisdkemper** [comment]
That's fixed it, thanks!
