### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'run_command' 

### ISSUE THREAD

**Issue by mavener** [SublimeText/SublimeHg#13]
I installed Sublime Hg on Mountain Lion with the Package Conrol.

When I try to run any command (for example "status") I get this error:

SublimeHg: 
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "./sublime_hg.py", line 120, in run
  File "./sublime_hg.py", line 38, in run_hg_cmd
AttributeError: 'NoneType' object has no attribute 'run_command'

**Comment by guillermooo** [comment]
Please try this and see if that works first:

https://bitbucket.org/guillermooo/sublimehg/downloads/SublimeHg.sublime-package

**Comment by mavener** [comment]
Hi, 

I tried the bitbucket version, but I'm still getting the same error.

**Comment by guillermooo** [comment]
Thanks for that. Unfotunately I cannot test on OS X, but I'll try to find the problem.

**Comment by guillermooo** [comment]
Can you also please run `hg version` and report back?

**Comment by mavener** [comment]
$ hg version
Mercurial Distributed SCM (version 1.9)

**Comment by guillermooo** [comment]
Are you running the command on a file inside a repo? Sounds like there's no repo under the file's dir.

**Comment by mavener** [comment]
Yes, the file I'm running it on is inside a repo. The error written in the console looks the same when I run it on a file without a repo, but there is one small difference: When I run the command on a non repo file I get a "SublimeHt: No repo found here." message in the status bar. I don't get this message when running the command on a repo file. 

But yes, the error message in the console is the same in both cases.

**Comment by guillermooo** [comment]
Can you describe the exact steps you take to start SublimeHg, including how you open the repo folder (via shell, graphical browser...)? I cannot reproduce this on Windows and as I've said before, I cannot test on OS X. I will give it a go on Ubuntu too,  but things have always worked fine there too.

**Comment by mavener** [comment]
Here is a short screencast. It starts with sublimetext open with the error message. I restart Sublime Text, open a file in a repo, run the Status command and get the error. https://dl.dropbox.com/u/314365/sublimehg.mov

**Comment by guillermooo** [comment]
Ha, I always forget how awesome Dropbox is. Thanks for that. Only thing I can think of now is that hg isn't visible in the PATH for Sublime Text. Please open the ST console, type the following in and tell me if you get any errors:

```
import subprocess
subprocess.call("hg")
```

**Comment by mavener** [comment]
this is the result: https://img.skitch.com/20120911-7w5yi5yf9sgy4fds4bp6tc584.jpg
(Skitch is nice too :-))

**Comment by guillermooo** [comment]
I see... No love for Windows lusrs, though. :) Ok, it seems to be a PATH problem indeed.

Check this out:

http://stackoverflow.com/questions/135688/setting-environment-variables-in-os-x

I'll try to show a friendlier error in that case.

**Comment by mavener** [comment]
I added the full path to my hg in settings

"packages.sublime_hg.hg_exe": "/opt/local/bin/hg" 

and now it works.

Thanx for help
