### ISSUE TITLE
ST2: console error thrown for distutils

### ISSUE THREAD

**Issue by ashemedai** [SublimeText/SublimeHg#17]
Currently getting this in Sublime Text 2 just after it has loaded/started:

``` python
Reloading plugin C:\Users\39865jru\AppData\Roaming\Sublime Text 2\Packages\SublimeHg\setup.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\setup.py", line 11, in <module>
    from distutils import log, dir_util, dep_util, file_util, archive_util
ImportError: No module named distutils
```

**Comment by guillermooo** [comment]
This should only happen if you're pulling from source. The packaged distribution (linked in the readme) should not have this problem.

It's harmless, but ugly. In the future I will get rid of _setup.py_ altogether, I think.

**Comment by ashemedai** [comment]
Ah, well, not willingly pulled from source, but in the case of installing it via Package Control will always create this then.

**Comment by ashemedai** [comment]
Closing this. So much has changed in the intermediate years.
