### ISSUE TITLE
Sublime Text 3

### ISSUE THREAD

**Issue by ApollonGT** [SublimeText/SublimeHg#18]
In Sublime Text 3, although it has been installed it's like it hasn't.

this is the console response:

show_sublime_hg_menu
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'show_sublime_hg_menu' is not defined

**Comment by guillermooo** [comment]
Port will happen here:

https://github.com/guillermooo/SublimeHg
