### ISSUE TITLE
Pull command doesn't work correctly

### ISSUE THREAD

**Issue by chrisdkemper** [SublimeText/SublimeHg#5]
When I try and perform a pull using SublimeHG it doesn't seem to work properly. I've checked the console and it does seem to perform the command, but there's not indication for whether or not the request has been successful or fails. In addition, because the process doesn't seem to timeout it means you cannot use any other parts of the plugin, but it says theres already a process running.

Any idea what could be causing the problem?

Cheers,
Chris

**Comment by guillermooo** [comment]
Long-running commands have this problem. I have to look into it.

**Comment by guillermooo** [comment]
Commands like this one run now in a separate process, so this problem should not occur any more. Not ideal, but it works for now.
