### ISSUE TITLE
hg qnew patch-name from command prompt doesn't work

### ISSUE THREAD

**Issue by lucasr** [SublimeText/SublimeHg#6]
As well as other commands that involve further user input, such as hg qref -e.

**Comment by guillermooo** [comment]
Which `$EDITOR` or `$HGEDITOR` are you using? The aforementioned commands work fine for me. I use Notepad to edit commit messages, because Sublime Text won't block on Windows. On other platforms (at least OSX), there are flags available to make the calling process wait until Sublime Text exits.

**Comment by lucasr** [comment]
@guillermooo Thanks for your reply. My hg editor is vim which requires a terminal to run. Wouldn't it be better if SublimeHg simply opened a tab in ST itself for editing those things? I don't know if it's actually possible to do it with current ST plugin API, just thinking out loud about what would be the best UX for those operations.

Suggestion: maybe add a setting key to define the editor to use? This way users would be able to override the global hg editor with something that makes more sense in the context of ST.

**Comment by guillermooo** [comment]
What's your platform?

**Comment by lucasr** [comment]
Linux (Fedora)
