### ISSUE TITLE
Provide a command console

### ISSUE THREAD

**Issue by lucasr** [SublimeText/SublimeHg#7]
Here's a quick feature request. Although the command prompt is really nice, it would be much nicer if SublimeHg provided a command console where you'd type hg commands a see their output straight away in the console. Better UI for typing multiple commands in succession.

**Comment by guillermooo** [comment]
This is a great idea, but AFAIK it won't be easily done with the current API. There isn't such thing as a custom console for plugins. A separate buffer could be used instead, but that means SublimeHg should keep track of the buffer the Hg console was started from. For comparison, at the moment, it just relies on the buffer with the input focus.

**Comment by viperfx** [comment]
Can you do it the way Will Bond does it with his SFTP plugin? Instead of opening a new window on each commit, output the message to a console window?

**Comment by guillermooo** [comment]
Unfortunately this won't work well for long outputs and it will preclude the use of custom syntax defs. Btw, this is how things used to work in the beginning, but I found it quite suboptimal... I think a dedicated console is the way to go, although I'm not sure how to implement it yet.
